import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import NProgressProvider from '@/components/NProgressProvider';
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "EduSphere",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <NProgressProvider />
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
